# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egreeting.proto\x12\x11\x61\x64vanced_greeting\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xdd\x02\n\x0f\x41\x64vancedGreeter\x12L\n\x08SayHello\x12\x1f.advanced_greeting.HelloRequest\x1a\x1d.advanced_greeting.HelloReply\"\x00\x12T\n\x0eGreetManyTimes\x12\x1f.advanced_greeting.HelloRequest\x1a\x1d.advanced_greeting.HelloReply\"\x00\x30\x01\x12O\n\tLongGreet\x12\x1f.advanced_greeting.HelloRequest\x1a\x1d.advanced_greeting.HelloReply\"\x00(\x01\x12U\n\rGreetEveryone\x12\x1f.advanced_greeting.HelloRequest\x1a\x1d.advanced_greeting.HelloReply\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeting_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=37
  _HELLOREQUEST._serialized_end=65
  _HELLOREPLY._serialized_start=67
  _HELLOREPLY._serialized_end=96
  _ADVANCEDGREETER._serialized_start=99
  _ADVANCEDGREETER._serialized_end=448
# @@protoc_insertion_point(module_scope)
